### ISSUE TITLE
Doesn't work with 1.0.4 version of remote loader gem

### ISSUE THREAD

**Issue by nielsjansendk** [d12/graphql-remote_loader_example#1]
If you change the gemfile and replace

`gem 'graphql-remote_loader', '~> 1.0.0'`

with

`gem 'graphql-remote_loader', '~> 1.0.4'`

this application fails. The error is: 

```
ArgumentError (wrong number of arguments (given 2, expected 1)):

app/graphql/loaders/github_loader.rb:16:in `query'
app/controllers/graphql_controller.rb:12:in `execute'


```
I'd like to see and example of how to use the latest version of the gem.

**Comment by d12** [comment]
Thanks for the report @nielsjansendk , you should be good to go now!
